# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  main: openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  showConsole: true
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#23649c"
    typography:
      code:
        fontFamily: 'Ubuntu Mono, monospace'
        fontSize: '12px'
      headings:
        fontFamily: 'Montserrat, sans-serif'
        fontWeight: '400'
      links:
        color: "#d8006c"
    rightPanel:
      backgroundColor: "#44475a"
      borderRadius: "10px"
    codeBlock:
      backgroundColor: "#282a36"